---
swagger: "2.0"
info:
  description: "Sample service for user registration and accounting. Use http://localhost:8080/v3/api-docs/ to access generated raw docs and http://localhost:8080/swagger-ui/index.html for ui "
  version: "1.0-SNAPSHOT"
  title: "Pulkovo Service"
  contact:
    email: "arifolth@gmail.com"
  license:
    name: "GPLv3"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "user"
  description: "Operations on user"
  externalDocs:
    description: "Sample sample sample"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /statistics:
    get:
      tags:
      - "statistics"
      summary: "Server statistics"
      description: "Server statistics"
      operationId: "getStatistics"
      produces:
        - "application/json"
      parameters:
        - name: "reqStatus"
          in: "query"
          description: "Requested status"
          required: true
          type: "integer"
        - name: "adults"
          in: "query"
          description: "Include adults"
          required: false
          type: "boolean"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Statistics"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be fetched. Use user1 for testing. "
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "Update user status."
      operationId: "updateUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/Status"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Status"
        400:
          description: "Invalid user supplied"
        404:
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "integer"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Create user."
      operationId: "createUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        400:
          description: "Invalid data supplied"
        404:
          description: "User not found"
definitions:
  ModelApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
  Statistics:
    type: "object"
    properties:
      overall:
        type: "integer"
        format: "int32"
      statusUsers:
        type: "array"
        items:
          $ref: "#/definitions/User"
      ageUsers:
        type: "array"
        items:
          $ref: "#/definitions/User"
      midAge:
        type: "integer"
        format: "int32"
  Status:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      userOldStatus:
        type: "integer"
        format: "int32"
        description: "User old Status"
      userNewStatus:
        type: "integer"
        format: "int32"
        description: "User new Status"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      username:
        type: "string"
      birthday:
        type: "string"
        format: "date"
      age:
        type: "integer"
        format: "int32"
      email:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
